from typing import TypedDict, List, Optional, Dict, Any

class Section(TypedDict):
    title: str
    content: str

class DocumentGenerationState(TypedDict):
    # Session Metadata
    session_id: str
    project_id: str
    
    # Context
    meeting_minutes: Optional[str]  # Raw input
    
    # Document Progress
    sections_outline: List[str]     # List of section titles (e.g., ["Scope", "Requirements"])
    current_section_index: int      # Pointer to which section we are working on
    
    # Current Draft State
    current_section_content: str    # The content generated by LLM for the current section
    feedback_action: Optional[str]  # 'approve' or 'regenerate'
    feedback_notes: Optional[str]   # User comments
    
    # Final Output
    final_document: List[Section]   # List of approved sections
    is_complete: bool